#!/bin/sh
### BEGIN INIT INFO
# Provides:          aerolith
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: SCD41 CO2/temp/humidity display
### END INIT INFO

NAME=aerolith
PIDFILE=/var/run/$NAME.pid
DAEMON=/usr/bin/aerolith

case "$1" in
  start)
    echo "Starting $NAME..."
    start-stop-daemon -S -q -m -b -p "$PIDFILE" -x "$DAEMON"
    ;;
  stop)
    echo "Stopping $NAME..."
    start-stop-daemon -K -q -p "$PIDFILE"
    ;;
  restart|reload|force-reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac

exit 0
